globals:
  React: true
  PropTypes: true

env:
  es2017: true
  browser: true
  commonjs: true
  jest: true

extends: [
    'htmlacademy/es6',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended'
]

parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

settings:
  react:
    version: '16'

rules:
  object-curly-spacing: ['error', 'always', { 'arraysInObjects': true, 'objectsInObjects': true }]
  quote-props: ['error', 'as-needed']
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
